name: 'Setup Xamarin'
author: 'Maxim Lobanov'
description: 'Set up your GitHub Actions workflow with a specific version of Xamarin & Mono'
inputs:
  mono-version:
    description: 'Version of Mono to select'
    required: false
  xamarin-ios-version:
    description: 'Version of Xamarin.iOS to select'
    required: false
  xamarin-mac-version:
    description: 'Version of Xamarin.Mac to select'
    required: false
  xamarin-android-version:
    description: 'Version of Xamarin.Android to select'
    required: false
  xcode-version:
    description: 'Version of Xcode to use with Xamarin.iOS and Xamarin.Mac'
    required: false
runs:
  using: 'node12'
  main: 'dist/index.js'
branding:
  icon: 'code'
  color: 'yellow'