on: [push]

jobs:
  setup-xamarin:
    runs-on: ubuntu-latest
    name: Validate setup-xamarin task
    steps:
    - name: setup-xamarin
      id: test
      uses: maxim-lobanov/setup-xamarin@implement-first-version